import type { Comment } from './comment.entity'

export const mockComments: Comment[] = [
  {
    commentId: 1,
    boardId: 1,
    userName: '절약왕123',
    nowme: '자린고비형',
    content: '저도 같은 고민 중이에요!',
    likeCount: 12,
    createdAt: '2025-07-23',
  },
  {
    commentId: 2,
    boardId: 1,
    userName: '금융초보',
    nowme: '새싹투자형',
    content: '펀드나 ETF는 어떤가요?',
    likeCount: 7,
    createdAt: '2025-07-23',
  },
  {
    commentId: 3,
    boardId: 2,
    userName: '카드달인',
    nowme: '욜로형',
    content: '요즘 현대카드 혜택 괜찮아요!',
    likeCount: 3,
    createdAt: '2025-07-22',
  },
  {
    commentId: 4,
    boardId: 2,
    userName: '실속파',
    nowme: '소확행형',
    content: '전 국민카드 씁니다. 영화 할인 최고예요.',
    likeCount: 5,
    createdAt: '2025-07-22',
  },
  {
    commentId: 5,
    boardId: 3,
    userName: '투자고민중',
    nowme: '공격투자형',
    content: '요즘은 예금보다 MMF나 CMA도 고려해보세요.',
    likeCount: 4,
    createdAt: '2025-07-21',
  },
  {
    commentId: 6,
    boardId: 4,
    userName: '절약고수',
    nowme: '자린고비형',
    content: '세일 정보 공유해요~',
    likeCount: 8,
    createdAt: '2025-07-20',
  },
  {
    commentId: 7,
    boardId: 5,
    userName: '부자될래',
    nowme: '자린고비형',
    content: '자동이체 적금은 진짜 꿀입니다.',
    likeCount: 10,
    createdAt: '2025-07-19',
  },
]